[tool.poetry]
name = "shynet"
version = "0.13.1"
description = "Modern, privacy-friendly, and cookie-free web analytics."
authors = ["R. Miles McCain <github@sendmiles.email>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0"
Flask-SQLAlchemy = "^3.1"
Flask-Migrate = "^4.0"
Flask-Login = "^0.6.3"
Flask-WTF = "^1.2"
Flask-Mail = "^0.10"
Flask-Caching = "^2.3"
Flask-Babel = "^4.0"
Flask-Admin = "^1.6"
Flask-DebugToolbar = "^0.16"
SQLAlchemy = "^2.0"
alembic = "^1.13"
itsdangerous = "^2.2"
email-validator = "^2.1"
geoip2 = "^4.2.0"
whitenoise = "^6.6"
celery = "^5.2.2"
PyYAML = "^6.0"
user-agents = "^2.2.0"
gunicorn = "^22.0"
psycopg2-binary = "^2.9.2"
redis = "^5.0"
pycountry = "^24.6"
html2text = "^2024.2"
python-dotenv = "^1.0"

[tool.poetry.dev-dependencies]
pytest-sugar = "^0.9.4"
factory-boy = "^3.2.0"
pytest = "^8.0"
coverage = "^7.4"
mypy = "^1.9"

[tool.pytest.ini_options]
testpaths = ["shynet"]
python_files = ["test_*.py", "tests_*.py"]
python_classes = ["Test*"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
