from flask_babel import lazy_gettext as _
from flask_wtf import FlaskForm
from markupsafe import Markup
from wtforms import RadioField, StringField, TextAreaField, URLField
from wtforms.validators import DataRequired, Length, Optional, URL, ValidationError

from accounts.models import EmailAddress
from core.models import Service, User, _validate_network_list, _validate_regex
from shynet import settings
from shynet.exceptions import ValidationError as ShynetValidationError
from shynet.extensions import db


def _bool_coerce(value):
    if isinstance(value, bool):
        return value
    return str(value) == "True"


class BooleanRadioField(RadioField):
    """A yes/no radio group backed by a boolean model column."""

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("coerce", _bool_coerce)
        kwargs.setdefault("choices", [(True, _("Yes")), (False, _("No"))])
        super().__init__(*args, **kwargs)

    def process_data(self, value):
        self.data = _bool_coerce(value) if value is not None else self.default


class ServiceForm(FlaskForm):
    name = StringField(
        _("Name"),
        validators=[DataRequired(), Length(max=64)],
        description=_("What should the service be called?"),
    )
    link = URLField(
        _("Link"),
        validators=[Optional(), URL()],
        description=_("What's the service's primary URL?"),
    )
    collaborators = StringField(
        _("Collaborators"),
        validators=[Optional()],
        description=_(
            "Which users on this Shynet instance should have read-only access to this service? (Comma separated list of emails.)"
        ),
    )
    respect_dnt = BooleanRadioField(
        _("Respect DNT"),
        default=True,
        description=Markup(
            _(
                "Should visitors who have enabled <a href='https://en.wikipedia.org/wiki/Do_Not_Track'>Do Not Track</a> be excluded from all data?"
            )
        ),
    )
    collect_ips = BooleanRadioField(
        _("Collect ips"),
        default=False if settings.BLOCK_ALL_IPS else True,
        description=_("IP address collection is disabled globally by your administrator.")
        if settings.BLOCK_ALL_IPS
        else _(
            "Should individual IP addresses be collected? IP metadata (location, host, etc) will still be collected."
        ),
        render_kw={"disabled": True} if settings.BLOCK_ALL_IPS else None,
    )
    ignored_ips = StringField(
        _("Ignored IP addresses"),
        validators=[Optional()],
        description=_(
            "A comma-separated list of IP addresses or IP ranges (IPv4 and IPv6) to exclude from tracking (e.g., '192.168.0.2, 127.0.0.1/32')."
        ),
    )
    ignore_robots = BooleanRadioField(
        _("Ignore robots"),
        default=False,
        description=_("Should sessions generated by bots be excluded from tracking?"),
    )
    hide_referrer_regex = StringField(
        _("Hide specific referrers"),
        validators=[Optional()],
        description=Markup(
            _(
                "Any referrers that match this <a href='https://regexr.com/'>RegEx</a> will not be listed in the referrer summary. Sessions will still be tracked normally. No effect if left blank."
            )
        ),
    )
    origins = StringField(
        _("Allowed origins"),
        validators=[DataRequired()],
        description=_(
            "At what origins does the service operate? Use commas to separate multiple values. This sets CORS headers, so use '*' if you're not sure (or don't care)."
        ),
    )
    script_inject = TextAreaField(
        _("Additional injected JS"),
        validators=[Optional()],
        description=_(
            "Optional additional JavaScript to inject at the end of the Shynet script. This code will be injected on every page where this service is installed."
        ),
        render_kw={"class": "font-mono", "rows": 5},
    )

    def __init__(self, *args, obj=None, **kwargs):
        super().__init__(*args, obj=obj, **kwargs)
        self.instance = obj
        self.collaborator_users = []
        if obj is not None and not self.is_submitted():
            # `get_initial_for_field` used to turn the related users into emails.
            self.collaborators.data = ", ".join(
                [user.email for user in (obj.collaborators or [])]
            )
        if obj is None and not self.is_submitted():
            self.origins.data = self.origins.data or "*"

    def validate_ignored_ips(self, field):
        try:
            _validate_network_list(field.data or "")
        except ShynetValidationError as error:
            raise ValidationError(str(error))

    def validate_hide_referrer_regex(self, field):
        try:
            _validate_regex(field.data or "")
        except ShynetValidationError as error:
            raise ValidationError(str(error))

    def validate_collect_ips(self, field):
        # Forces collect IPs to be false if it is disabled globally
        if settings.BLOCK_ALL_IPS:
            field.data = False

    def validate_collaborators(self, field):
        collaborators = []
        users_to_emails = (
            {}
        )  # maps users to the email they are listed under as a collaborator
        for collaborator_email in (field.data or "").split(","):
            email = collaborator_email.strip()
            if email == "":
                continue
            collaborator_email_linked = EmailAddress.lookup(email)
            if collaborator_email_linked is None:
                raise ValidationError(f"Email '{email}' is not registered")
            user = collaborator_email_linked.user
            if user in collaborators:
                raise ValidationError(
                    f"The emails '{email}' and '{users_to_emails[user]}' both correspond to the same user"
                )
            users_to_emails[user] = email
            collaborators.append(collaborator_email_linked.user)
        self.collaborator_users = collaborators

    def save(self, instance=None, commit=True):
        """Apply the cleaned data to `instance` (creating it when absent)."""
        service = instance if instance is not None else Service()
        service.name = self.name.data
        service.link = self.link.data or ""
        service.respect_dnt = self.respect_dnt.data
        service.collect_ips = False if settings.BLOCK_ALL_IPS else self.collect_ips.data
        service.ignored_ips = self.ignored_ips.data or ""
        service.ignore_robots = self.ignore_robots.data
        service.hide_referrer_regex = self.hide_referrer_regex.data or ""
        service.origins = self.origins.data
        service.script_inject = self.script_inject.data or ""
        service.collaborators = list(self.collaborator_users)
        db.session.add(service)
        if commit:
            db.session.commit()
        return service
